name: Update README

on:
  push:
    paths:
      - '**/*.py'
      - '**/*.c'
      - '**/*.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate README
        run: python generate_readme.py

      - name: Commit and push if changes
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Fetch the newest history
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
          
          # Hard reset to the remote state without losing changes
          git reset --soft origin/main

          # If there are changes, add and commit them
          git add README.md
          COMMIT_MSG="Update README"
          git commit -m "$COMMIT_MSG" || echo "No changes to commit"
          
          # Push changes using PAT
          git push --set-upstream https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} main
