name: Update README

on:
  push:
    paths:
      - '**/*.py'
      - '**/*.c'
      - '**/*.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate README
        run: python generate_readme.py

      - name: Commit and push if changes
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Ensure the local main branch is up to date
          git pull --rebase origin main
          
          # Stage any changes
          git add README.md
          
          # Commit changes if there are any
          git commit -m "Update README" || echo "No changes to commit"
          
          # Push the changes using the PAT
          git push --set-upstream https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} main
